name: prototype
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  provider: ^6.1.2
  flutter_dotenv: ^6.0.0
  http: ^1.2.2
  elevenlabs_agents:
    git:
      url: https://github.com/seahyc/elevenlabs-flutter-fork.git
  permission_handler: ^12.0.1
  pluralize: ^0.0.8
  google_fonts: ^6.2.1
  flutter_signin_button: ^2.0.0
  audioplayers: ^6.1.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  supabase: ^2.0.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/sounds/
    - assets/images/
